framework:
    translator: { fallbacks: ["%locale%"] }
    secret: '%env(APP_SECRET)%'
    validation:
        enabled: true
        enable_annotations: true
    annotations:
        enabled: true
    form:
        enabled: true
        legacy_error_messages: false
    csrf_protection: true
    session:
        handler_id: ~
    serializer:
        enabled: true
        enable_annotations: true
        mapping:
            paths: [ '%kernel.project_dir%/config/serialization' ]

when@dev:
    framework:
        profiler: { only_exceptions: false }
#        annotations:
#            enabled: true
#        validation:
#            enable_annotations: true
#        serializer:
#            enable_annotations: true

when@test: &framework_test
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@test_cached: *framework_test
