App\Entity\Image:
    type: entity
    table: app_slider_image
    manyToMany:
        owner:
            targetEntity: App\Entity\Slider
            inversedBy: images
            joinColumn:
                name: owner_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
