App\Entity\Slider:
    type: entity
    table: sylius_slider
    manyToMany:
        images:
            targetEntity: App\Entity\Image
            mappedBy: owner
            orphanRemoval: true
            cascade:
                - all
